/**
 * Demo — "what did the topology look like DURING the incident?" An OTel
 * backend answers this badly: dashboards show CURRENT topology, and a trace
 * search finds individual requests, not "the shape of the service graph an
 * hour ago." This package answers it almost for free, because the graph this
 * library materializes is bitemporal: `asOfRecorded` reconstructs the belief
 * as of any past recorded instant, and a service topology is just a belief
 * like any other.
 *
 * The scenario: `checkout` is deployed under three different `service.name`
 * spellings over its life (`checkout-svc`, `checkout`, `checkout.prod`) —
 * exactly the mess real telemetry accumulates across redeploys and
 * environments. Partway through the stream, the `checkout.prod` deployment
 * starts calling a `fraud-detection` service it never called before.
 *
 * Two things are asserted, not narrated:
 *   (1) entity resolution collapses all three spellings into one `Service`
 *       node, with every spelling retained as a `ServiceAlias`;
 *   (2) `asOfRecorded` at an anchor before the new call shows the old
 *       topology; at an anchor after, it shows the new one.
 *
 * Every span here is generated by the REAL `@opentelemetry/sdk-trace-node`
 * SDK (see `fixtures/incident-scenario.ts` for the traffic script) — nothing
 * in this file is hand-written span JSON. Fully offline: no collector, no
 * network, an in-memory SQLite belief store.
 *
 * Run with:  pnpm demo
 */
import { checkpointGraph, consume, graphProjector, mockShapeSource, typeGraphCheckpoints, type ShapeChange } from "@nicia-ai/agent-stream-graph";
import { type RecordedInstant, recordedInstantRevision } from "@nicia-ai/typegraph";
import { createLocalSqliteStore } from "@nicia-ai/typegraph/sqlite/local";
import { context, SpanKind, trace, type Tracer } from "@opentelemetry/api";
import { resourceFromAttributes } from "@opentelemetry/resources";
import { SimpleSpanProcessor } from "@opentelemetry/sdk-trace-base";
import { NodeTracerProvider } from "@opentelemetry/sdk-trace-node";
import { ATTR_SERVICE_NAME } from "@opentelemetry/semantic-conventions";
import { pathToFileURL } from "node:url";

import { decode } from "./decode.js";
import { GraphSpanExporter, toShapeChanges, type SpanRecord } from "./exporter.js";
import { serviceGraph } from "./graph.js";
import { BEFORE_INCIDENT_REQUESTS, INCIDENT_REQUESTS, type Request } from "../fixtures/incident-scenario.js";

const RULE = "━".repeat(74);
function section(title: string): void {
  console.log("\n" + RULE);
  console.log(` ${title}`);
  console.log(RULE);
}

const STREAM_NAME = "otel-collector";
const SPAN_SHAPE = "span";

// ============================================================
// (a) Generating spans with the real SDK — no hand-written span JSON
// ============================================================

/**
 * One `NodeTracerProvider` per raw service name — exactly how a real fleet
 * works: a redeploy under a new `service.name` genuinely is a distinct
 * resource emitting its own spans, which is why `checkout`, `checkout-svc`,
 * and `checkout.prod` need three separate tracers here rather than one
 * tracer reused with a changing label.
 */
function makeTracerCache(exporter: GraphSpanExporter): (rawServiceName: string) => Tracer {
  const tracers = new Map<string, Tracer>();
  return (rawServiceName: string): Tracer => {
    const existing = tracers.get(rawServiceName);
    if (existing !== undefined) return existing;
    const provider = new NodeTracerProvider({
      resource: resourceFromAttributes({ [ATTR_SERVICE_NAME]: rawServiceName }),
      spanProcessors: [new SimpleSpanProcessor(exporter)],
    });
    const tracer = provider.getTracer(rawServiceName);
    tracers.set(rawServiceName, tracer);
    return tracer;
  };
}

/**
 * Plays one inbound request through the real SDK: a root SERVER span at the
 * entry service, then a CLIENT/SERVER span pair per hop, each hop's parent
 * context threaded EXPLICITLY through `startSpan`'s third argument — no
 * global context manager or `provider.register()` needed, which is what lets
 * several independent `NodeTracerProvider`s coexist in one offline process.
 */
function runRequest(tracerFor: (rawServiceName: string) => Tracer, request: Request): void {
  const entrySpan = tracerFor(request.entryRaw).startSpan(request.entryOperation, { kind: SpanKind.SERVER });
  let activeContext = trace.setSpan(context.active(), entrySpan);
  let fromRaw = request.entryRaw;
  for (const step of request.calls) {
    const clientSpan = tracerFor(fromRaw).startSpan(
      `${step.operation} (client)`,
      { kind: SpanKind.CLIENT, attributes: { [step.peerAttribute]: step.toRaw } },
      activeContext,
    );
    const clientContext = trace.setSpan(activeContext, clientSpan);
    const serverSpan = tracerFor(step.toRaw).startSpan(step.operation, { kind: SpanKind.SERVER }, clientContext);
    serverSpan.end();
    clientSpan.end();
    activeContext = trace.setSpan(clientContext, serverSpan);
    fromRaw = step.toRaw;
  }
  entrySpan.end();
}

function offsetAt(changes: readonly ShapeChange<SpanRecord>[], index: number): string {
  const change = changes[index];
  if (change === undefined) throw new Error(`no span record at index ${index} — the scenario produced fewer spans than expected`);
  return change.offset;
}

type CallEdge = Readonly<{ caller: string; callee: string }>;

function edgeKey(edge: CallEdge): string {
  return `${edge.caller} -> ${edge.callee}`;
}

function printTopology(label: string, edges: readonly CallEdge[]): void {
  console.log(`\n  ${label}`);
  if (edges.length === 0) {
    console.log("    (no calls edges)");
    return;
  }
  for (const edge of [...edges].sort((a, b) => edgeKey(a).localeCompare(edgeKey(b)))) {
    console.log(`    ${edge.caller} --calls--> ${edge.callee}`);
  }
}

export async function main(): Promise<void> {
  console.log(RULE);
  console.log(" OTel spans -> bitemporal service topology — what did it look like DURING the incident?");
  console.log(RULE);

  section("(a) Generating spans with the real OTel SDK, offline, over fixtures/");
  const exporter = new GraphSpanExporter();
  const tracerFor = makeTracerCache(exporter);
  for (const request of BEFORE_INCIDENT_REQUESTS) runRequest(tracerFor, request);
  const beforeCount = exporter.records.length;
  console.log(`\n  ${BEFORE_INCIDENT_REQUESTS.length} pre-incident requests -> ${beforeCount} spans`);
  for (const request of INCIDENT_REQUESTS) runRequest(tracerFor, request);
  const afterCount = exporter.records.length;
  console.log(`  ${INCIDENT_REQUESTS.length} incident-window requests -> ${afterCount - beforeCount} more spans (${afterCount} total)`);

  const changes = toShapeChanges(exporter.records, SPAN_SHAPE);
  const beforeOffset = offsetAt(changes, beforeCount - 1);
  const afterOffset = offsetAt(changes, afterCount - 1);
  console.log(`\n  "before" offset: @${beforeOffset} (end of pre-incident traffic)`);
  console.log(`  "after"  offset: @${afterOffset} (end of the incident window)`);

  section("(b) Feeding spans into this library's durable consumer");
  const belief = await createLocalSqliteStore(serviceGraph, { store: { history: true, coalesceUnchangedUpserts: true } });
  const cursor = await createLocalSqliteStore(checkpointGraph);
  const book = typeGraphCheckpoints(cursor);

  try {
    const source = mockShapeSource(STREAM_NAME, changes);
    const project = graphProjector(serviceGraph, decode);
    const result = await consume({ source, store: belief, checkpoints: book, project });
    console.log(`\n  consumed ${result.processed} spans, cursor at @${result.lastOffset}`);

    section("(c) Entity resolution — three spellings, one canonical Service");
    const allServices = await belief.query().from("Service", "s").select((c) => ({ id: c.s.id })).execute();
    const aliasRows = await belief
      .query()
      .from("ServiceAlias", "a")
      .traverse("aliasOf", "e")
      .to("Service", "s")
      .select((c) => ({ observed: c.a.observedName, canonical: c.s.id }))
      .execute();
    const checkoutAliases = aliasRows.filter((row) => row.canonical === "checkout").map((row) => row.observed).sort();

    console.log(`\n  ${allServices.length} canonical Service nodes: ${allServices.map((s) => s.id).sort().join(", ")}`);
    console.log(`\n  every spelling ever observed for the "checkout" Service:`);
    for (const observed of checkoutAliases) console.log(`    "${observed}" --aliasOf--> checkout`);

    const expectedAliases = ["checkout", "checkout-svc", "checkout.prod"];
    const collapsed = checkoutAliases.length === expectedAliases.length && expectedAliases.every((name) => checkoutAliases.includes(name));
    if (!collapsed) {
      throw new Error(
        `entity resolution did not collapse the three spellings: expected aliases [${expectedAliases.join(", ")}], got [${checkoutAliases.join(", ")}]`,
      );
    }
    console.log(`\n  >>> COLLAPSED: 3 spellings, 1 canonical "checkout" Service node. <<<`);

    section("(d) Incident timeline — asOfRecorded before vs. after the new dependency");
    const beforeAnchor = await book.anchorFor(STREAM_NAME, beforeOffset);
    const afterAnchor = await book.anchorFor(STREAM_NAME, afterOffset);
    if (beforeAnchor === undefined || afterAnchor === undefined) {
      throw new Error(`missing checkpoint anchor for offset @${beforeOffset} or @${afterOffset}`);
    }

    async function callEdgesAt(anchor: RecordedInstant): Promise<readonly CallEdge[]> {
      return belief
        .asOfRecorded(anchor)
        .query()
        .from("Service", "caller")
        .traverse("calls", "e")
        .to("Service", "callee")
        .select((c) => ({ caller: c.caller.id, callee: c.callee.id }))
        .execute();
    }

    const topologyBefore = await callEdgesAt(beforeAnchor);
    const topologyAfter = await callEdgesAt(afterAnchor);
    console.log(`\n  @${beforeOffset} (rev ${recordedInstantRevision(beforeAnchor)}) — topology BEFORE the incident window:`);
    printTopology("calls edges:", topologyBefore);
    console.log(`\n  @${afterOffset} (rev ${recordedInstantRevision(afterAnchor)}) — topology AFTER the incident window:`);
    printTopology("calls edges:", topologyAfter);

    const target: CallEdge = { caller: "checkout", callee: "fraud-detection" };
    const hadItBefore = topologyBefore.some((edge) => edge.caller === target.caller && edge.callee === target.callee);
    const hasItAfter = topologyAfter.some((edge) => edge.caller === target.caller && edge.callee === target.callee);
    if (hadItBefore) {
      throw new Error(`demo setup is broken: checkout -> fraud-detection already existed at @${beforeOffset}, before the incident window`);
    }
    if (!hasItAfter) {
      throw new Error(`incident timeline is broken: checkout -> fraud-detection is missing at @${afterOffset}, after the incident window`);
    }
    console.log(`\n  >>> checkout -> fraud-detection: ABSENT at @${beforeOffset}, PRESENT at @${afterOffset}. <<<`);
    console.log(`      The current graph has moved on past both moments — asOfRecorded reconstructed`);
    console.log(`      each one anyway.`);

    console.log("\n" + RULE);
    console.log(" A dependency graph is a belief like any other. Bitemporal storage means");
    console.log(" \"what did it look like then\" was never a separate feature to build.");
    console.log(RULE + "\n");
  } finally {
    await Promise.allSettled([belief.close(), cursor.close()]);
  }
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
  });
}
